sudo: false
language: php

php:
  - 5.5

matrix:
    allow_failures:

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - phpunit --coverage-text

notifications:
  slack: huuinn:PKunf4lmOqZYlXvGHjOfuOhy